# Generated by Django 5.2.9 on 2026-01-17 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_system', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
