# Generated by Django 5.2.9 on 2026-01-17 21:42

import django.core.validators
import event_system.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_system', '0002_delete_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to=event_system.models.event_banner_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])]),
        ),
    ]
