# Generated by Django 5.2.9 on 2026-01-05 16:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_system', '0002_event_approved_at_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
