# Generated by Django 5.2.9 on 2026-01-11 18:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_system', '0006_alter_registration_event'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='date',
            new_name='date_start',
        ),
        migrations.AddField(
            model_name='event',
            name='date_end',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
